MatchingTranslations:
  enabled: true
TemplateLength:
  enabled: true
SchemaJsonFormat:
  enabled: true
RequiredLayoutThemeAppExtension:
  enabled: true
RequiredTemplateSections:
  enabled: true
RequiredThemeAppExtensions:
  enabled: true
